# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: ssh into droplet
    runs-on: ubuntu-latest
    steps:
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "production"
        
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd production
          docker-compose up --build -d
